Fall back to running tests with SQLite

diff --git a/bin/run-behat-tests b/bin/run-behat-tests
--- a/bin/run-behat-tests
+++ b/bin/run-behat-tests
@@ -19,6 +19,76 @@ if [[ "$@" == *"--help"* ]]; then
     exit $ret
 fi
 
+# POSIX compliant function to check if a string is numeric.
+is_numeric() {
+    case $1 in
+        ''|*[!0-9]*) return 1;;  # returns 1 if not numeric
+        *) return 0;;            # returns 0 if numeric
+    esac
+}
+
+# If DB type is already set to SQLite, there's nothing to do.
+if [ "${WP_CLI_TEST_DBTYPE-}" = "sqlite" ]; then
+	echo "WP_CLI_TEST_DBTYPE is set to 'sqlite', skipping database check."
+else
+	# Check for database client and connectivity.
+	DB_CLIENT=""
+	if command -v mysql &> /dev/null; then
+		DB_CLIENT="mysql"
+	elif command -v mariadb &> /dev/null; then
+		DB_CLIENT="mariadb"
+	fi
+
+	if [ -z "${DB_CLIENT}" ]; then
+		echo "Warning: Could not find 'mysql' or 'mariadb' client."
+		echo "The tests will continue to be run, but with WP_CLI_TEST_DBTYPE=sqlite."
+		export WP_CLI_TEST_DBTYPE=sqlite
+	else
+		HOST_STRING=''
+		if [ -n "${WP_CLI_TEST_DBHOST}" ]; then
+			case ${WP_CLI_TEST_DBHOST##*[]]} in
+				(*:*) HOST=${WP_CLI_TEST_DBHOST%:*} PORT=${WP_CLI_TEST_DBHOST##*:};;
+				(*)   HOST=${WP_CLI_TEST_DBHOST};;
+			esac
+			HOST_STRING="-h${HOST}"
+			if [ -n "${PORT}" ]; then
+				# If the port is not numeric, then we assume it is a socket path.
+				if is_numeric "${PORT}"; then
+					HOST_STRING="${HOST_STRING} --port=${PORT} --protocol=tcp"
+				else
+					HOST_STRING="${HOST_STRING} --socket=${PORT} --protocol=socket"
+				fi
+			fi
+		fi
+
+		USER=${WP_CLI_TEST_DBUSER:-wp_cli_test}
+
+		if [ -z "${WP_CLI_TEST_DBPASS+x}" ]; then
+			# not set, use default
+			PASSWORD="password1"
+		else
+			# is set, use its value (could be empty)
+			PASSWORD="${WP_CLI_TEST_DBPASS}"
+		fi
+
+		PASSWORD_ARG=""
+		if [ -n "${PASSWORD}" ]; then
+			PASSWORD_ARG="-p${PASSWORD}"
+		fi
+
+		DBNAME=${WP_CLI_TEST_DBNAME:-wp_cli_test}
+
+		# We need to test the connection.
+		# Let's try to connect to the specific test database.
+		if ! ${DB_CLIENT} ${HOST_STRING} --user="${USER}" ${PASSWORD_ARG} --execute="USE \`${DBNAME}\`;" 2>/dev/null; then
+			echo "Warning: Could not connect to the MySQL/MariaDB database."
+			echo "Please make sure the database is running and run 'composer prepare-tests' once to set it up."
+			echo "The tests will continue to be run, but with WP_CLI_TEST_DBTYPE=sqlite."
+			export WP_CLI_TEST_DBTYPE=sqlite
+		fi
+	fi
+fi
+
 # Turn WP_VERSION into an actual number to make sure our tags work correctly.
 if [ "${WP_VERSION-latest}" = "latest" ]; then
 	export WP_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r ".offers[0].current")
